### ISSUE TITLE
Can't make the SDK working

### ISSUE THREAD

**Issue by bangank36** [intercom/intercom-php#225] opened 2017-07-06 03:58 UTC
For feature requests please contact us at team@intercom.io

## Version info
  - intercom-php version: Latest commit c9f84d8
  - PHP version: 5.6

## Expected behavior
The IntercomClient to be init
## Actual behavior
Error on screen:
http://prntscr.com/fs7c9n
## Steps to reproduce (as granular as possible, including screenshots where appropriate)
 1. Install Composer
 2. Run Composer update
 3. http://prntscr.com/fs7w32

**Comment by choran** [comment] 2017-08-28 12:54
Hi @bangank36 
I was wondering if you were still having issues here ... I was unable to reproduce your error.
We do have docker images which you can use to run your local code without the need for any setup on your local machine. That might be the easiest way to start if you are having issue. You can find out more [here](https://developers.intercom.com/v2.0/docs/docker-sdk-environments). 
Cathal

**Comment by choran** [comment] 2017-09-07 15:41
Hi @bangank36 
Just checking if you had any update here?
I will close this for now but if you do have an update please feel free to re-open.
Thanks
Cathal

**Closed by choran** 2017-09-07 15:41 UTC
Labels: question
