### ISSUE TITLE
Visitor conversion

### ISSUE THREAD

**Issue by merlijnbigtree** [intercom/intercom-php#292] opened 2019-11-15 16:22 UTC
- intercom-php version: 4.2
  - Intercom API version: 1.1 (also tried 1.4)
  - PHP version: 7.3.1

Nothing seems to happen when trying to convert a visitor to a user (or a lead) :

$client->visitors->convertVisitor([
		"visitor" => [
			"user_id" => "{visitor_id}"
		],
		"user" => [
			"email" => "test@testing.com"
		],
		"type" => "user"
]);

and

$client->visitors->convertVisitor([
		"visitor" => [
			"user_id" => "{visitor_id}"
		],
		"type" => "lead"
]);

(where {visitor_id} is a valid id obtained through Intercom('getVisitorId'); )

**Comment by GabrielAnca** [comment] 2020-07-21 14:44
Hey @merlijnbigtree :wave: 

What do you get back from the API call? We would need to see the response code and message to understand if anything went wrong with the SDK.

This is unlikely an issue with the SDK itself, it may be something to do with the API or product itself. If you haven't already and are still seeing issues with this, I'd recommend reaching out to the support team using the Messenger on https://intercom.com

As this isn't an issue with the SDK and I can't reproduce it, I'm going to close this out. If you get any exception from the SDK please let us know and reopen the issue, we'll be happy to help!

**Closed by GabrielAnca** 2020-07-21 14:44 UTC
