### ISSUE TITLE
Can not install intercom/intercom-php in laravel 8

### ISSUE THREAD

**Issue by mizan3008** [intercom/intercom-php#319] opened 2020-09-21 08:14 UTC
I am trying to install `"intercom/intercom-php": "^4.4"` in laravel 8, but getting error

## Version info
  - intercom-php version: 4.4
  - Intercom API version: 2.2
  - PHP version: 7.3

## Expected behavior
Should successfully install

## Actual behavior
![image](https://user-images.githubusercontent.com/6143192/93744901-660e9a80-fc14-11ea-9820-367c39ae1b88.png)

## Steps to reproduce (as granular as possible, including screenshots where appropriate)
 1. Install laravel 8 with recommended `"guzzlehttp/guzzle": "^7.0.1"` 
 2. Try to install intercom/intercom-php package by running `composer require intercom/intercom-php "^4.4"`

**Comment by GabrielAnca** [comment] 2020-09-21 08:19
Hi @mizan3008 👋 

In order to install intercom-php you need to specify an [HTTPlug client implementation](https://packagist.org/providers/php-http/client-implementation). There is no support for Guzzle7 yet, so that will give you a version conflict when you install it.

You can use any available alternative, for example, CURL: `composer require intercom/intercom-php php-http/curl-client`

Closing as a dupe of https://github.com/intercom/intercom-php/issues/317, but feel free to reopen this issue if you are still facing issues instaling this library 😃

**Closed by GabrielAnca** 2020-09-21 08:19 UTC

**Comment by m-elewa** [comment] 2021-06-30 00:37
if you want to use Guzzle HTTP, use this forked repo https://github.com/m-elewa/intercom-php

**Comment by baj84** [comment] 2021-08-02 21:03
Hi do I need to do anything to tell intercom-php to use the curl client instead of guzzle?
